name: Cypress End-to-End Tests

on:
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🏗 Set up NodeJS 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
          cache: 'npm'


      - name: 💻 Run Cypress
        uses: cypress-io/github-action@v5
        with:
          start: npm run cy:test
          wait-on: http://127.0.0.1:9200/
          wait-on-timeout: 40000
          browser: chrome
          headed: false
          record: true
          parallel: true
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          flags: E2E
