name: Deploy to Cloudflare

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Build Quasar app
        run: npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/pwa --project-name=celebrityfanalyzer
          
      - name: print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
  
  lighthouse:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Install dependencies
          run: npm install
  
        - name: Lighthouse mobile audit
          run: npm run lhci:mobile --target=${{ env.DEPLOYMENT_URL }}
          env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  
        - name: Lighthouse desktop audit
          run: npm run lhci:desktop --target=${{ env.DEPLOYMENT_URL }}
          env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

