name: Lighthouse Performance Test
on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for Cloudflare Preview Deployment
        id: wait_deployment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          # Check the latest Cloudflare deployment for a preview URL
          echo "Fetching latest deployment for Cloudflare environment preview..."
          until PREVIEW_URL=$(npx wrangler deployments --project-name celebrityfanalyzer \
            | jq -r '.[0] | select(.env == "preview") | .url')
          do
            echo "Waiting for Cloudflare deployment to be active..."
            sleep 10
          done

          # Verify if URL is captured
          if [[ -z "$PREVIEW_URL" ]]; then
            echo "Error: Preview URL is empty. Deployment may have failed."
            exit 1
          fi

          echo "Preview URL: $PREVIEW_URL"
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Lighthouse mobile audit
        run: npm run lhci:mobile --target=${{ env.PREVIEW_URL }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Lighthouse desktop audit
        run: npm run lhci:desktop --target=${{ env.PREVIEW_URL }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
