name: Lighthouse Performance Test
on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for Cloudflare Preview Deployment
        id: wait_deployment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the most recent deployment data for debugging
          echo "Fetching deployment data for debugging..."
          gh api "repos/${{ github.repository }}/deployments" \
            -H "Accept: application/vnd.github.ant-man-preview+json,application/vnd.github.flash-preview+json" > deployment_data.json
          cat deployment_data.json

          # Check if the latest deployment is in the preview environment and active
          until PREVIEW_URL=$(gh api "repos/${{ github.repository }}/deployments" \
            -H "Accept: application/vnd.github.ant-man-preview+json,application/vnd.github.flash-preview+json" \
            -q '.[0] | select(.environment == "preview") | select(.state == "active") | .url')
          do
            echo "Waiting for deployment..."
            sleep 10
          done

          # Verify if URL is captured
          if [[ -z "$PREVIEW_URL" ]]; then
            echo "Error: Preview URL is empty. Check deployment_data.json for details."
            exit 1
          fi

          echo "Preview URL: $PREVIEW_URL"
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: lighthouse mobile audit
        run: npm run lhci:mobile --target=${{ env.PREVIEW_URL }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: lighthouse desktop audit
        run: npm run lhci:desktop --target=${{ env.PREVIEW_URL }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
