name: Lighthouse Performance Test
on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for Cloudflare Preview Deployment
        id: wait_deployment
        run: |
          until gh api \
            "repos/${{ github.repository }}/deployments" \
            -H "Accept: application/vnd.github.ant-man-preview+json,application/vnd.github.flash-preview+json" \
            -q '.[0] | select(.environment == "preview") | select(.state == "active") | .url'
          do
            echo "Waiting for deployment..."
            sleep 10
          done
          PREVIEW_URL=$(gh api \
            "repos/${{ github.repository }}/deployments" \
            -H "Accept: application/vnd.github.ant-man-preview+json,application/vnd.github.flash-preview+json" \
            -q '.[0] | select(.environment == "preview") | .url')
          echo "Preview URL: $PREVIEW_URL"
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: lighthouse mobile audit
        run: npm run lhci:mobile --target=${{ env.PREVIEW_URL }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: lighthouse desktop audit
        run: npm run lhci:desktop --target=${{ env.PREVIEW_URL }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
