name: Vitest Unit Tests

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🏗 Set up NodeJS 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
          cache: 'npm'

      - name: 💻 Run Vitest
        run: |
          npm ci
          npm run test:unit:coverage

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: unittests
